wandb_version: 1

learning_rate:
  desc: null
  value: 4.4259487676293826e-06
epochs:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.5192046596526917
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709637996.007354
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
